/* eslint-disable */
// tslint:disable
/**
 * Postcodes.io
 * Postcodes.io allows UK postcode data to be queried over a JSON HTTP API.

Postcodes.io is an open sourced project maintained by Ideal Postcodes.

It is a free resource, allowing developers to search, reverse geocode and extract UK postcode and associated data.

 *
 * OpenAPI spec version: 1.0.0
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */
import { Buffer } from "buffer";

export namespace Api {
	export interface BulkPostcodeLookupOrBulkReverseGeocoding200Response extends Api.ServerResponseBody {
		result?: Api.PostcodeDataReverseGeocoding[];
	}

	export type BulkPostcodeLookupOrBulkReverseGeocodingRequest = Api.BulkPostcodeLookupOrBulkReverseGeocodingRequest.ObjectValue | Api.BulkPostcodeLookupOrBulkReverseGeocodingRequest.ObjectValue2;
	
	/**
	 * @export
	 * @namespace BulkPostcodeLookupOrBulkReverseGeocodingRequest
	 */
	export namespace BulkPostcodeLookupOrBulkReverseGeocodingRequest {
		export interface ObjectValue {
			postcodes?: string[];
		}
	
		export interface ObjectValue2 {
			geolocations?: Api.Geolocation[];
		}
	
	}

	export interface Geolocation {
		/**
		 * @description <h3 id="latitude">Latitude</h3>
		 *  <p>The WGS84 latitude given the Postcode&#39;s national grid reference.</p>
		 * @type {number}
		 * @memberof Geolocation
		 */
		latitude: number;
		/**
		 * @description <h3 id="longitude">Longitude</h3>
		 *  <p>The WGS84 longitude given the Postcode&#39;s national grid reference.</p>
		 * @type {number}
		 * @memberof Geolocation
		 */
		longitude: number;
		/**
		 * @description <p>A comma separated whitelist of attributes to be returned in the result object(s), e.g. <code>filter=postcode,longitude,latitude</code>. <code>null</code> responses will continue to return <code>null</code>. If no attributes match the result object, an empty object is returned </p>
		 * @type {string}
		 * @memberof Geolocation
		 */
		filter?: string;
		/**
		 * @description <p>Limits number of postcodes matches to return. Defaults to 10. Needs to be less than 100.</p>
		 * @type {number}
		 * @memberof Geolocation
		 */
		limit?: number;
		/**
		 * @description <p>Limits number of postcodes matches to return. Defaults to 100m. Needs to be less than 2,000m. </p>
		 * @type {number}
		 * @memberof Geolocation
		 */
		radius?: number;
		/**
		 * @description <p>Search up to 20km radius, but subject to a maximum of 10 results</p>
		 * @type {boolean}
		 * @memberof Geolocation
		 */
		widesearch?: boolean;
	}

	export interface NearestOutcode200Response extends Api.ServerResponseBody {
		result?: Api.OutcodeData[];
	}

	export interface NearestPostcode200Response extends Api.ServerResponseBody {
		result?: Api.PostcodeDataReverseGeocoding[];
	}

	/**
	 * <h3 id="outcode-data-ordnance-survey-postcode-directory-dataset">Outcode Data (Ordnance Survey Postcode Directory Dataset)</h3>
	 * <p>Data returned by the <code>/outcodes</code> API</p>
	 */
	export interface OutcodeData {
		/**
		 * @description <h3 id="county">County</h3>
		 *  <p>The current counties under the outcode.</p>
		 * @type {(string | null)[]}
		 * @memberof OutcodeData
		 */
		'admin_county'?: (string | null)[];
		/**
		 * @description <h3 id="district">District</h3>
		 *  <p>The current district/unitary authorites under the outcode.</p>
		 * @type {(string | null)[]}
		 * @memberof OutcodeData
		 */
		'admin_district'?: (string | null)[];
		/**
		 * @description <h3 id="ward">Ward</h3>
		 *  <p>The current administrative/electoral areas under the outcode</p>
		 * @type {(string | null)[]}
		 * @memberof OutcodeData
		 */
		'admin_ward'?: (string | null)[];
		/**
		 * @description <h3 id="country">Country</h3>
		 *  <p>The countries included in the outcode.</p>
		 * @type {string[]}
		 * @memberof OutcodeData
		 */
		country?: string[];
		/**
		 * @description <h3 id="eastings">Eastings</h3>
		 *  <p>The Ordnance Survey postcode grid reference Easting to 1 metre resolution. Grid references for postcodes in Northern Ireland relate to the Irish Grid system. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof OutcodeData
		 */
		eastings?: number | null;
		/**
		 * @description <h3 id="latitude">Latitude</h3>
		 *  <p>The WGS84 latitude given the Postcode&#39;s national grid reference. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof OutcodeData
		 */
		latitude?: number | null;
		/**
		 * @description <h3 id="longitude">Longitude</h3>
		 *  <p>The WGS84 longitude given the Postcode&#39;s national grid reference. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof OutcodeData
		 */
		longitude?: number | null;
		/**
		 * @description <h3 id="northings">Northings</h3>
		 *  <p>The Ordnance Survey postcode grid reference Northing to 1 metre resolution. Grid references for postcodes in Northern Ireland relate to the Irish Grid system. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof OutcodeData
		 */
		northings?: number | null;
		/**
		 * @description <h3 id="outward-code">Outward Code</h3>
		 *  <p>The outward code is the part of the postcode before the single space in the middle. It is between two and four characters long. A few outward codes are non-geographic, not divulging where mail is to be sent. Examples of outward codes include &quot;L1&quot;, &quot;W1A&quot;, &quot;RH1&quot;, &quot;RH10&quot; or &quot;SE1P&quot;.</p>
		 * @type {string}
		 * @memberof OutcodeData
		 */
		outcode?: string;
		/**
		 * @description <h3 id="parish-englandcommunity-wales">Parish (England)/community (Wales)</h3>
		 *  <p>The parishes included in the outcode.</p>
		 * @type {(string | null)[]}
		 * @memberof OutcodeData
		 */
		parish?: (string | null)[];
		'parliamentary_constituency'?: (string | null)[];
	}

	export interface OutcodeReverseGeocoding200Response extends Api.ServerResponseBody {
		result?: (Api.OutcodeData[]) | null;
	}

	export interface OutwardCodeLookup200Response extends Api.ServerResponseBody {
		/**
		 * @description <h3 id="outcode-data-ordnance-survey-postcode-directory-dataset">Outcode Data (Ordnance Survey Postcode Directory Dataset)</h3>
		 *  <p>Data returned by the <code>/outcodes</code> API</p>
		 * @type {Api.OutcodeData}
		 * @memberof OutwardCodeLookup200Response
		 */
		result?: Api.OutcodeData;
	}

	export interface PlaceLookup200Response extends Api.ServerResponseBody {
		/**
		 * @description <h3 id="places-data-ordnance-survey-open-names-dataset">Places Data (Ordnance Survey Open Names Dataset)</h3>
		 *  <p>Data returned by the /places API</p>
		 *  <p>Note: Some fields may be null if not applicable or populated.</p>
		 * @type {Api.PlacesData}
		 * @memberof PlaceLookup200Response
		 */
		result?: Api.PlacesData;
	}

	export interface PlaceQuery200Response extends Api.ServerResponseBody {
		result?: Api.PlacesData[];
	}

	/**
	 * <h3 id="places-data-ordnance-survey-open-names-dataset">Places Data (Ordnance Survey Open Names Dataset)</h3>
	 * <p>Data returned by the /places API</p>
	 * <p>Note: Some fields may be null if not applicable or populated.</p>
	 */
	export interface PlacesData {
		/**
		 * @description <h3 id="code">code</h3>
		 *  <p>A unique identifier that enables records to be identified easily. The identifier will be persistent for all LocalTypes except Section of Named Road and Section of Numbered Road.</p>
		 * @type {string}
		 * @memberof PlacesData
		 */
		code?: string;
		/**
		 * @description <h3 id="country">Country</h3>
		 *  <p>OS Places relates to Great Britain only. i.e. <code>England</code>, <code>Scotland</code>, <code>Wales</code>.</p>
		 * @type {string}
		 * @memberof PlacesData
		 */
		country?: string;
		/**
		 * @description <h3 id="administrative-area">Administrative Area</h3>
		 *  <p>The name of the County (non-metropolitan or Metropolitan), Unitary Authority or Greater London Authority administrative area that the point geometry for feature is within or nearest to.</p>
		 * @type {string | null}
		 * @memberof PlacesData
		 */
		'county_unitary'?: string | null;
		/**
		 * @description <h3 id="administrative-area-type">Administrative Area Type</h3>
		 *  <p>Classifies the type of administrative unit.</p>
		 * @type {string | null}
		 * @memberof PlacesData
		 */
		'county_unitary_type'?: string | null;
		/**
		 * @description <h3 id="district-or-borough">District or Borough</h3>
		 *  <p>The name of the District, Metropolitan District or London Borough administrative unit that the point geometry for the feature is within.</p>
		 * @type {string | null}
		 * @memberof PlacesData
		 */
		'district_borough'?: string | null;
		/**
		 * @description <h3 id="borough-type">Borough Type</h3>
		 *  <p>Classifies the type of administrative unit.</p>
		 * @type {string | null}
		 * @memberof PlacesData
		 */
		'district_borough_type'?: string | null;
		/**
		 * @description <h3 id="eastings">Eastings</h3>
		 *  <p>The Ordnance Survey postcode grid reference Easting to 1 metre resolution; blank for postcodes in the Channel Islands and the Isle of Man.</p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		eastings?: number;
		/**
		 * @description <h3 id="latitude">Latitude</h3>
		 *  <p>The WGS84 latitude given the Postcode&#39;s national grid reference.</p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		latitude?: number;
		/**
		 * @description <h3 id="local-type">Local Type</h3>
		 *  <p>The Ordnance Survey classification for the named place being represented by the specific feature, e.g. <code>City</code>, <code>Town</code>, <code>Village</code>, <code>Hamlet</code>, <code>Other Settlement</code>, <code>Suburban Area</code>.</p>
		 * @type {string}
		 * @memberof PlacesData
		 */
		'local_type'?: string;
		/**
		 * @description <h3 id="longitude">Longitude</h3>
		 *  <p>The WGS84 longitude given the Postcode&#39;s national grid reference.</p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		longitude?: number;
		/**
		 * @description <h3 id="maximum--minimum-northings--eastings">Maximum &amp; Minimum, Northings &amp; Eastings</h3>
		 *  <p>Bounding box or Minimum Bounding Rectangle (MBR) for roads and settlements. For Settlements and Sections of Named and Numbered Roads, the MBR gives a representation of the extent of these features and is not snapped to the real world extent. </p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		'max_eastings'?: number;
		/**
		 * @description <h3 id="maximum--minimum-northings--eastings">Maximum &amp; Minimum, Northings &amp; Eastings</h3>
		 *  <p>Bounding box or Minimum Bounding Rectangle (MBR) for roads and settlements. For Settlements and Sections of Named and Numbered Roads, the MBR gives a representation of the extent of these features and is not snapped to the real world extent. </p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		'min_eastings'?: number;
		/**
		 * @description <h3 id="maximum--minimum-northings--eastings">Maximum &amp; Minimum, Northings &amp; Eastings</h3>
		 *  <p>Bounding box or Minimum Bounding Rectangle (MBR) for roads and settlements. For Settlements and Sections of Named and Numbered Roads, the MBR gives a representation of the extent of these features and is not snapped to the real world extent. </p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		'max_northings'?: number;
		/**
		 * @description <h3 id="maximum--minimum-northings--eastings">Maximum &amp; Minimum, Northings &amp; Eastings</h3>
		 *  <p>Bounding box or Minimum Bounding Rectangle (MBR) for roads and settlements. For Settlements and Sections of Named and Numbered Roads, the MBR gives a representation of the extent of these features and is not snapped to the real world extent. </p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		'min_northings'?: number;
		/**
		 * @description <h3 id="name">Name</h3>
		 *  <p>The proper noun that applies to the real world entity. Names that are prefixed by the definite article are not formatted for alphabetical sorting, that is, ‘The Pennines’ not ‘Pennines, The’.</p>
		 * @type {string}
		 * @memberof PlacesData
		 */
		'name_1'?: string;
		/**
		 * @description <h3 id="language-of-name">Language of Name</h3>
		 *  <p>The language type is only set where more than one name exists, e.g. cym (Welsh), eng (English), gla (Scottish Gaelic).</p>
		 * @type {string | null}
		 * @memberof PlacesData
		 */
		'name_1_lang'?: string | null;
		/**
		 * @description <h3 id="name-in-case-of-multiple-languages">Name (in case of multiple languages)</h3>
		 *  <p>The proper noun that applies to the real world entity. Names that are prefixed by the definite article are not formatted for alphabetical sorting, that is, ‘The Pennines’ not ‘Pennines, The’.</p>
		 * @type {string | null}
		 * @memberof PlacesData
		 */
		'name_2'?: string | null;
		/**
		 * @description <h3 id="language-of-name">Language of Name</h3>
		 *  <p>The language type is only set where more than one name exists, e.g. cym (Welsh), eng (English), gla (Scottish Gaelic).</p>
		 * @type {string | null}
		 * @memberof PlacesData
		 */
		'name_2_lang'?: string | null;
		/**
		 * @description <h3 id="northings">Northings</h3>
		 *  <p>The Ordnance Survey postcode grid reference Northing to 1 metre resolution; blank for postcodes in the Channel Islands and the Isle of Man.</p>
		 * @type {number}
		 * @memberof PlacesData
		 */
		northings?: number;
		/**
		 * @description <h3 id="outward-code">Outward Code</h3>
		 *  <p>The outward code is the part of the postcode before the single space in the middle. It is between two and four characters long. A few outward codes are non-geographic, not divulging where mail is to be sent. Examples of outward codes include &quot;L1&quot;, &quot;W1A&quot;, &quot;RH1&quot;, &quot;RH10&quot; or &quot;SE1P&quot;.</p>
		 * @type {string}
		 * @memberof PlacesData
		 */
		outcode?: string;
		/**
		 * @description <h3 id="region">Region</h3>
		 *  <p>The name of the European Region (was Government O ice Region) that the point geometry for the feature is within or nearest to.</p>
		 * @type {string}
		 * @memberof PlacesData
		 */
		region?: string;
	}

	export interface PostcodeAutocomplete200Response extends Api.ServerResponseBody {
		result?: (string[]) | null;
	}

	/**
	 * <h3 id="postcode-data-ordnance-survey-postcode-directory-dataset">Postcode Data (Ordnance Survey Postcode Directory Dataset)</h3>
	 * <p>Data points returned by the <code>/postcodes</code> and <code>/outcodes</code> API</p>
	 * <p>Note: Some fields may be null if not applicable or populated.</p>
	 */
	export interface PostcodeData {
		/**
		 * @description <h3 id="county">County</h3>
		 *  <p>The current county to which the postcode has been assigned.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'admin_county'?: string | null;
		/**
		 * @description <h3 id="district">District</h3>
		 *  <p>The current district/unitary authority to which the postcode has been assigned.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'admin_district'?: string | null;
		/**
		 * @description <h3 id="ward">Ward</h3>
		 *  <p>The current administrative/electoral area to which the postcode has been assigned.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'admin_ward'?: string | null;
		/**
		 * @description <h3 id="sub-icb-location-loc-local-health-board-lhb-community-health-partnership-chp-local-commissioning-group-lcg-primary-healthcare-directorate-phd">Sub ICB Location (LOC)/ Local Health Board (LHB)/ Community Health Partnership (CHP)/ Local Commissioning Group (LCG)/ Primary Healthcare Directorate (PHD)</h3>
		 *  <p>The code for the Sub ICB Locations in England, LHBs in Wales, CHPs in Scotland, LCG in Northern Ireland and PHD in the Isle of Man; there are no equivalent areas in the Channel Islands. This was formerly Clinical Commissioning Group. From July 2022, CCGs were replaced by Sub-ICB locations.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		ccg?: string | null;
		/**
		 * @description <h3 id="county-electoral-district">County Electoral District</h3>
		 *  <p>The county electoral division code for each English postcode. Pseudo codes are included for the remainder of the UK. The field will be null for English postcodes with no grid reference. English county councils use county electoral divisions (CED) to elect councillors. These CEDs must be confined within district boundaries, but need not be based on whole electoral wards. The only exceptions are the Isles of Scilly and the Greater London Authority (GLA). CEDs do not exist within UAs.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		ced?: string | null;
		/**
		 * @description <h3 id="returns-an-id-or-code-associated-with-the-postcode">Returns an ID or Code associated with the postcode</h3>
		 *  <p>Typically, these are a 9 character code known as an ONS Code or GSS Code. This is currently only available for districts, parishes, counties, CCGs, NUTS and wards.</p>
		 * @type {Api.PostcodeData.Codes}
		 * @memberof PostcodeData
		 */
		codes?: Api.PostcodeData.Codes;
		/**
		 * @description <h3 id="country">Country</h3>
		 *  <p>The country (i.e. one of the four constituent countries of the United Kingdom or the Channel Islands or the Isle of Man) to which each postcode is assigned.</p>
		 * @type {string}
		 * @memberof PostcodeData
		 */
		country?: string;
		/**
		 * @description <p>TODO: undocumented</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'date_of_introduction'?: string | null;
		/**
		 * @description <h3 id="eastings">Eastings</h3>
		 *  <p>The Ordnance Survey postcode grid reference Easting to 1 metre resolution. Grid references for postcodes in Northern Ireland relate to the Irish Grid system. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof PostcodeData
		 */
		eastings?: number | null;
		/**
		 * @description <h3 id="european-electoral-region">European Electoral Region</h3>
		 *  <p>The European Electoral Region code for each postcode.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'european_electoral_region'?: string | null;
		/**
		 * @description <h3 id="inward-code">Inward Code</h3>
		 *  <p>The inward part is the part of the postcode after the single space in the middle. It is three characters long. The inward code assists in the delivery of post within a postal district. Examples of inward codes include &quot;0NY&quot;, &quot;7GZ&quot;, &quot;7HF&quot;, or &quot;8JQ&quot;.</p>
		 * @type {string}
		 * @memberof PostcodeData
		 */
		incode?: string;
		/**
		 * @description <h3 id="latitude">Latitude</h3>
		 *  <p>The WGS84 latitude given the Postcode&#39;s national grid reference. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof PostcodeData
		 */
		latitude?: number | null;
		/**
		 * @description <h3 id="longitude">Longitude</h3>
		 *  <p>The WGS84 longitude given the Postcode&#39;s national grid reference. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof PostcodeData
		 */
		longitude?: number | null;
		/**
		 * @description <h3 id="2011-census-lower-layer-super-output-area-lsoa">2011 Census Lower Layer Super Output Area (LSOA)</h3>
		 *  <p>The 2011 Census lower layer SOA code for England and Wales, SOA code for Northern Ireland and data zone code for Scotland.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		lsoa?: string | null;
		/**
		 * @description <h3 id="2011-census-middle-layer-super-output-area-msoa">2011 Census Middle Layer Super Output Area (MSOA)</h3>
		 *  <p>The 2011 Census middle layer SOA (MSOA) code for England and Wales and intermediate zone for Scotland.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		msoa?: string | null;
		/**
		 * @description <h3 id="strategic-health-authority">Strategic Health Authority</h3>
		 *  <p>The health area code for the postcode.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'nhs_ha'?: string | null;
		/**
		 * @description <h3 id="northings">Northings</h3>
		 *  <p>The Ordnance Survey postcode grid reference Northing to 1 metre resolution. Grid references for postcodes in Northern Ireland relate to the Irish Grid system. May be null if geolocation not available.</p>
		 * @type {number | null}
		 * @memberof PostcodeData
		 */
		northings?: number | null;
		/**
		 * @description <h3 id="international-terratorial-levels-itl-former-nomenclature-of-units-for-territorial-statistics-nuts">International Terratorial Levels (ITL) (Former Nomenclature of Units for Territorial Statistics (NUTS)</h3>
		 *  <p>The national LAU1-equivalent code for each postcode. Pseudo codes are included for Channel Islands and Isle of Man. The field will otherwise be blank for postcodes with no grid reference.</p>
		 *  <p>As of May 2021. NUTS has changed to International Territorial Levels (ITL). Postcodes.io will report ITL in <code>nuts</code> and <code>codes.nuts</code> to preserve backwards compatibility.</p>
		 *  <p>Following the UK&#39;s withdrawal from the EU, a new UK-managed international statistical geography - ITL (International Territorial Levels) - was introduced from 1st January 2021, replacing the former NUTS classification. They align with international standards, enabling comparability both over time and internationally. To ensure continued alignment, the ITLs mirror the NUTS system. They also follow a similar review timetable - every three years.</p>
		 *  <p>NUTS is a hierarchical classification of spatial units that provides a breakdown of the European Union’s territory for producing regional statistics that are comparable across the Union.</p>
		 *  <p>The ITL area classification in the UK comprises current national administrative and electoral areas, except in Scotland where some ITL areas comprise whole and/or part Local Enterprise Regions.</p>
		 *  <p>The ONSPD contains the LAU1 code (9-character LAD/UA code for England, Wales and Northern Ireland and &#39;S30&#39; code for Scotland). A comprehensive lookup of LAU and ITL codes is included with the accompanying metadata.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		nuts?: string | null;
		/**
		 * @description <h3 id="outward-code">Outward Code</h3>
		 *  <p>The outward code is the part of the postcode before the single space in the middle. It is between two and four characters long. A few outward codes are non-geographic, not divulging where mail is to be sent. Examples of outward codes include &quot;L1&quot;, &quot;W1A&quot;, &quot;RH1&quot;, &quot;RH10&quot; or &quot;SE1P&quot;.</p>
		 * @type {string}
		 * @memberof PostcodeData
		 */
		outcode?: string;
		/**
		 * @description <h3 id="parish">Parish</h3>
		 *  <p>The smallest type of administrative area in England is the parish (also known as &#39;civil parish&#39;); the equivalent units in Wales are communities.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		parish?: string | null;
		/**
		 * @description <h3 id="westminster-parliamentary-constituency">Westminster Parliamentary Constituency</h3>
		 *  <p>The Westminster Parliamentary Constituency code for each postcode.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'parliamentary_constituency'?: string | null;
		/**
		 * @description <p>TODO: undocumented</p>
		 * @type {string}
		 * @memberof PostcodeData
		 */
		pfa?: string;
		/**
		 * @description <h3 id="postcode">Postcode</h3>
		 *  <p>All current (‘live’) postcodes within the United Kingdom, the Channel Islands and the Isle of Man, received monthly from Royal Mail. 2, 3 or 4-character outward code, single space and 3-character inward code.</p>
		 * @type {string}
		 * @memberof PostcodeData
		 */
		postcode?: string;
		/**
		 * @description <h3 id="primary-care-trust-pct">Primary Care Trust (PCT)</h3>
		 *  <p>The code for the Primary Care areas in England, LHBs in Wales, CHPs in Scotland, LCG in Northern Ireland and PHD in the Isle of Man; there are no equivalent areas in the Channel Islands. Care Trust/ Care Trust Plus (CT)/ local health board (LHB)/ community health partnership (CHP)/ local commissioning group (LCG)/ primary healthcare directorate (PHD).</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		'primary_care_trust'?: string | null;
		/**
		 * @description <h3 id="positional-quality">Positional Quality</h3>
		 *  <p>Shows the status of the assigned grid reference.</p>
		 *  <ul>
		 *  <li>1 = within the building of the matched address closest to the postcode mean</li>
		 *  <li>2 = as for status value 1, except by visual inspection of Landline maps (Scotland only)</li>
		 *  <li>3 = approximate to within 50m</li>
		 *  <li>4 = postcode unit mean (mean of matched addresses with the same postcode, but not snapped to a building)</li>
		 *  <li>5 = imputed by ONS, by reference to surrounding postcode grid references</li>
		 *  <li>6 = postcode sector mean, (mainly | PO Boxes)</li>
		 *  <li>8 = postcode terminated prior to Gridlink® initiative, last known ONS postcode grid reference1</li>
		 *  <li>9 = no grid reference available</li>
		 *  </ul>
		 * @type {number}
		 * @memberof PostcodeData
		 */
		quality?: number;
		/**
		 * @description <h3 id="region">Region</h3>
		 *  <p>The Region code for each postcode. The nine GORs were abolished on 1 April 2011 and are now known as ‘Regions’. They were the primary statistical subdivisions of England and also the areas in which the Government Offices for the Regions fulfilled their role. Each GOR covered a number of local authorities.</p>
		 * @type {string | null}
		 * @memberof PostcodeData
		 */
		region?: string | null;
	}
	
	/**
	 * @export
	 * @namespace PostcodeData
	 */
	export namespace PostcodeData {
		/**
		 * <h3 id="returns-an-id-or-code-associated-with-the-postcode">Returns an ID or Code associated with the postcode</h3>
		 * <p>Typically, these are a 9 character code known as an ONS Code or GSS Code. This is currently only available for districts, parishes, counties, CCGs, NUTS and wards.</p>
		 */
		export interface Codes {
			/**
			 * @description <h3 id="county">County</h3>
			 *  <p>The current county to which the postcode has been assigned.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			'admin_county'?: string | null;
			/**
			 * @description <h3 id="district">District</h3>
			 *  <p>The current district/unitary authority to which the postcode has been assigned.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			'admin_district'?: string | null;
			/**
			 * @description <h3 id="ward">Ward</h3>
			 *  <p>The current administrative/electoral area to which the postcode has been assigned.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			'admin_ward'?: string | null;
			/**
			 * @description <h3 id="sub-icb-location-loc-local-health-board-lhb-community-health-partnership-chp-local-commissioning-group-lcg-primary-healthcare-directorate-phd">Sub ICB Location (LOC)/ Local Health Board (LHB)/ Community Health Partnership (CHP)/ Local Commissioning Group (LCG)/ Primary Healthcare Directorate (PHD)</h3>
			 *  <p>The code for the Sub ICB Locations in England, LHBs in Wales, CHPs in Scotland, LCG in Northern Ireland and PHD in the Isle of Man; there are no equivalent areas in the Channel Islands. This was formerly Clinical Commissioning Group. From July 2022, CCGs were replaced by Sub-ICB locations.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			ccg?: string | null;
			/**
			 * @description <p>CCG Short Code. e.g. &quot;07N&quot;.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			'ccg_id'?: string | null;
			/**
			 * @description <h3 id="county-electoral-district">County Electoral District</h3>
			 *  <p>The county electoral division code for each English postcode. Pseudo codes are included for the remainder of the UK. The field will be null for English postcodes with no grid reference. English county councils use county electoral divisions (CED) to elect councillors. These CEDs must be confined within district boundaries, but need not be based on whole electoral wards. The only exceptions are the Isles of Scilly and the Greater London Authority (GLA). CEDs do not exist within UAs.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			ced?: string | null;
			/**
			 * @description <p>The LAU2 code associated with the postcode.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			lau2?: string | null;
			/**
			 * @description <h3 id="2011-census-lower-layer-super-output-area-lsoa">2011 Census Lower Layer Super Output Area (LSOA)</h3>
			 *  <p>The 2011 Census lower layer SOA code for England and Wales, SOA code for Northern Ireland and data zone code for Scotland.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			lsoa?: string | null;
			/**
			 * @description <h3 id="2011-census-middle-layer-super-output-area-msoa">2011 Census Middle Layer Super Output Area (MSOA)</h3>
			 *  <p>The 2011 Census middle layer SOA (MSOA) code for England and Wales and intermediate zone for Scotland.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			msoa?: string | null;
			/**
			 * @description <p>The ITL code associated with the postcode.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			nuts?: string | null;
			/**
			 * @description <h3 id="parish">Parish</h3>
			 *  <p>The smallest type of administrative area in England is the parish (also known as &#39;civil parish&#39;); the equivalent units in Wales are communities.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			parish?: string | null;
			/**
			 * @description <h3 id="westminster-parliamentary-constituency">Westminster Parliamentary Constituency</h3>
			 *  <p>The Westminster Parliamentary Constituency code for each postcode.</p>
			 * @type {string | null}
			 * @memberof Codes
			 */
			'parliamentary_constituency'?: string | null;
			/**
			 * @description <p>TODO: undocumented</p>
			 * @type {string}
			 * @memberof Codes
			 */
			pfa?: string;
		}
	
	}

	export interface PostcodeDataReverseGeocoding extends Api.PostcodeData {
		/**
		 * @description <p>Distance in metres from specified postode</p>
		 * @type {number}
		 * @memberof PostcodeDataReverseGeocoding
		 */
		distance?: number;
	}

	export interface PostcodeLookup200Response extends Api.ServerResponseBody {
		/**
		 * @description <h3 id="postcode-data-ordnance-survey-postcode-directory-dataset">Postcode Data (Ordnance Survey Postcode Directory Dataset)</h3>
		 *  <p>Data points returned by the <code>/postcodes</code> and <code>/outcodes</code> API</p>
		 *  <p>Note: Some fields may be null if not applicable or populated.</p>
		 * @type {Api.PostcodeData}
		 * @memberof PostcodeLookup200Response
		 */
		result?: Api.PostcodeData;
	}

	export interface PostcodeValidation200Response extends Api.ServerResponseBody {
		/**
		 * @description <p>true or false (meaning valid or invalid respectively)</p>
		 * @type {boolean}
		 * @memberof PostcodeValidation200Response
		 */
		result?: boolean;
	}

	export interface RandomPlace200Response extends Api.ServerResponseBody {
		/**
		 * @description <h3 id="places-data-ordnance-survey-open-names-dataset">Places Data (Ordnance Survey Open Names Dataset)</h3>
		 *  <p>Data returned by the /places API</p>
		 *  <p>Note: Some fields may be null if not applicable or populated.</p>
		 * @type {Api.PlacesData}
		 * @memberof RandomPlace200Response
		 */
		result?: Api.PlacesData;
	}

	export interface RandomPostcode200Response extends Api.ServerResponseBody {
		result?: Api.RandomPostcode200Response.Result;
	}
	
	/**
	 * @export
	 * @namespace RandomPostcode200Response
	 */
	export namespace RandomPostcode200Response {
		export interface Result2 extends Api.RandomPostcode200Response.IResult {
		}
	
		export interface IResult {
		}
		
		export interface Result extends Api.PostcodeData, Api.RandomPostcode200Response.IResult {
		}
	
	}

	export interface ReverseGeocodingLegacy200Response extends Api.ServerResponseBody {
		result?: (Api.PostcodeDataReverseGeocoding[]) | null;
	}

	export interface ReverseGeocodingOrPostcodeQuery200Response extends Api.ServerResponseBody {
		result?: (Api.PostcodeDataReverseGeocoding[]) | null;
	}

	/**
	 * <h3 id="scottish-postcode-data-scottish-postcode-directory">Scottish Postcode Data (Scottish Postcode Directory)</h3>
	 * <p>Data returned by the <code>/scotland/*</code> APIs</p>
	 */
	export interface ScottishPostcodeData {
		/**
		 * @description <h3 id="returns-an-id-or-code-associated-with-the-postcode">Returns an ID or Code associated with the postcode</h3>
		 *  <p>Typically, these are a 9 character code known as an ONS Code or GSS Code.</p>
		 * @type {Api.ScottishPostcodeData.Codes}
		 * @memberof ScottishPostcodeData
		 */
		codes?: Api.ScottishPostcodeData.Codes;
		/**
		 * @description <h3 id="postcode">Postcode</h3>
		 *  <p>Royal Mail postcode.</p>
		 * @type {string}
		 * @memberof ScottishPostcodeData
		 */
		postcode?: string;
		/**
		 * @description <h3 id="scottish-parliamentary-constituency">Scottish Parliamentary Constituency</h3>
		 *  <p>2014 Scottish Parliamentary Constituency.</p>
		 * @type {string | null}
		 * @memberof ScottishPostcodeData
		 */
		'scottish_parliamentary_constituency'?: string | null;
	}
	
	/**
	 * @export
	 * @namespace ScottishPostcodeData
	 */
	export namespace ScottishPostcodeData {
		/**
		 * <h3 id="returns-an-id-or-code-associated-with-the-postcode">Returns an ID or Code associated with the postcode</h3>
		 * <p>Typically, these are a 9 character code known as an ONS Code or GSS Code.</p>
		 */
		export interface Codes {
			/**
			 * @description <h3 id="scottish-parliamentary-constituency">Scottish Parliamentary Constituency</h3>
			 *  <p>2014 Scottish Parliamentary Constituency.</p>
			 * @type {string}
			 * @memberof Codes
			 */
			'scottish_parliamentary_constituency'?: string;
		}
	
	}

	export interface ScottishPostcodeLookup200Response extends Api.ServerResponseBody {
		/**
		 * @description <h3 id="scottish-postcode-data-scottish-postcode-directory">Scottish Postcode Data (Scottish Postcode Directory)</h3>
		 *  <p>Data returned by the <code>/scotland/*</code> APIs</p>
		 * @type {Api.ScottishPostcodeData}
		 * @memberof ScottishPostcodeLookup200Response
		 */
		result?: Api.ScottishPostcodeData;
	}

	export interface ServerErrorResponseBody extends Api.ServerResponseBody {
		error?: string;
	}

	export interface ServerResponseBody {
		/**
		 * @description <p>HTTP Status Code</p>
		 * @type {number}
		 * @memberof ServerResponseBody
		 */
		status?: number;
	}

	/**
	 * <h3 id="terminated-postcode-data-ordnance-survey-postcode-directory-dataset">Terminated Postcode Data (Ordnance Survey Postcode Directory Dataset)</h3>
	 * <p>Data returned by the <code>/terminated_postcodes/*</code> APIs</p>
	 */
	export interface TerminatedPostcodeData {
		/**
		 * @description <h3 id="latitude">Latitude</h3>
		 *  <p>The WGS84 latitude given the Postcode&#39;s national grid reference.</p>
		 * @type {number}
		 * @memberof TerminatedPostcodeData
		 */
		latitude?: number;
		/**
		 * @description <h3 id="longitude">Longitude</h3>
		 *  <p>The WGS84 longitude given the Postcode&#39;s national grid reference.</p>
		 * @type {number}
		 * @memberof TerminatedPostcodeData
		 */
		longitude?: number;
		/**
		 * @description <h3 id="termination-month">Termination month</h3>
		 *  <p>Month of termination of a postcode. 1-January, 2-February ... 12-December.</p>
		 * @type {number}
		 * @memberof TerminatedPostcodeData
		 */
		'month_terminated'?: number;
		/**
		 * @description <h3 id="postcode">Postcode</h3>
		 *  <p>All currently terminated postcodes within the United Kingdom, the Channel Islands and the Isle of Man, received every 3 months from Royal Mail. 2, 3 or 4-character outward code, single space and 3-character inward code.</p>
		 * @type {string}
		 * @memberof TerminatedPostcodeData
		 */
		postcode?: string;
		/**
		 * @description <h3 id="termination-year">Termination year</h3>
		 *  <p>Year of termination of a postcode.</p>
		 * @type {number}
		 * @memberof TerminatedPostcodeData
		 */
		'year_terminated'?: number;
	}

	export interface TerminatedPostcodeLookup200Response extends Api.ServerResponseBody {
		/**
		 * @description <h3 id="terminated-postcode-data-ordnance-survey-postcode-directory-dataset">Terminated Postcode Data (Ordnance Survey Postcode Directory Dataset)</h3>
		 *  <p>Data returned by the <code>/terminated_postcodes/*</code> APIs</p>
		 * @type {Api.TerminatedPostcodeData}
		 * @memberof TerminatedPostcodeLookup200Response
		 */
		result?: Api.TerminatedPostcodeData;
	}

}
